apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.10
  clusterID: cf23b116-dafc-4fc8-873b-1b33fc7e6c90
status:
  desired:
    version: 4.10.24
