---
apiVersion: image.openshift.io/v1     
kind: ImageStream
metadata:
  name: bgd
  namespace: et-sandbox
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: quay.io/redhatworkshops/bgd:latest
      importPolicy: {}
      referencePolicy:
        type: Local
