---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
spec:
  selector:
    matchLabels:
      app: nginx-hello
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:stable-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: nginx-conf
              mountPath: /usr/share/nginx/html/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: nginx-content
        configMap:
          name: nginx-content
          items:
            - key: index.html
              path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>This is a custom nginx welcome page</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>nginx on kubernetes!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello
  namespace: nginx-hello
spec:
  selector:
    app: nginx-hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx
  namespace: nginx-hello
spec:
  host: nginx-nginx-hello.apps.ocpdev.jdm4.com
  to:
    kind: Service
    name: nginx-hello
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None