---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
  namespace: nginx-hello
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>This is a custom nginx welcome page</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>nginx on homelab kubernetes!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>
